export const LANGUAGES = [
  { code: "ar", name: "Arabic", nativeName: "العربية" },
  { code: "en", name: "English", nativeName: "English" },
  { code: "fr", name: "French", nativeName: "Français" },
  { code: "es", name: "Spanish", nativeName: "Español" },
  { code: "de", name: "German", nativeName: "Deutsch" },
  { code: "pt", name: "Portuguese", nativeName: "Português" },
  { code: "it", name: "Italian", nativeName: "Italiano" },
  { code: "nl", name: "Dutch", nativeName: "Nederlands" },
  { code: "ru", name: "Russian", nativeName: "Русский" },
  { code: "ja", name: "Japanese", nativeName: "日本語" },
  { code: "ko", name: "Korean", nativeName: "한국어" },
  { code: "zh", name: "Chinese", nativeName: "中文" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी" },
  { code: "ur", name: "Urdu", nativeName: "اردو" },
  { code: "tr", name: "Turkish", nativeName: "Türkçe" },
  { code: "fa", name: "Persian", nativeName: "فارسی" },
  { code: "id", name: "Indonesian", nativeName: "Bahasa Indonesia" },
  { code: "ms", name: "Malay", nativeName: "Bahasa Melayu" },
  { code: "th", name: "Thai", nativeName: "ไทย" },
  { code: "vi", name: "Vietnamese", nativeName: "Tiếng Việt" },
  { code: "pl", name: "Polish", nativeName: "Polski" },
  { code: "sv", name: "Swedish", nativeName: "Svenska" },
  { code: "no", name: "Norwegian", nativeName: "Norsk" },
  { code: "da", name: "Danish", nativeName: "Dansk" },
  { code: "fi", name: "Finnish", nativeName: "Suomi" },
  { code: "cs", name: "Czech", nativeName: "Čeština" },
  { code: "ro", name: "Romanian", nativeName: "Română" },
  { code: "uk", name: "Ukrainian", nativeName: "Українська" },
  { code: "el", name: "Greek", nativeName: "Ελληνικά" },
  { code: "he", name: "Hebrew", nativeName: "עברית" },
  { code: "sw", name: "Swahili", nativeName: "Kiswahili" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা" },
  { code: "ta", name: "Tamil", nativeName: "தமிழ்" },
  { code: "te", name: "Telugu", nativeName: "తెలుగు" },
  { code: "mr", name: "Marathi", nativeName: "मराठी" },
  { code: "gu", name: "Gujarati", nativeName: "ગુજરાતી" },
  { code: "kn", name: "Kannada", nativeName: "ಕನ್ನಡ" },
  { code: "ml", name: "Malayalam", nativeName: "മലയാളം" },
  { code: "pa", name: "Punjabi", nativeName: "ਪੰਜਾਬੀ" },
  { code: "hy", name: "Armenian", nativeName: "Հայերեն" },
  { code: "ka", name: "Georgian", nativeName: "ქართული" },
  { code: "am", name: "Amharic", nativeName: "አማርኛ" },
  { code: "ha", name: "Hausa", nativeName: "Hausa" },
  { code: "yo", name: "Yoruba", nativeName: "Yorùbá" },
  { code: "ig", name: "Igbo", nativeName: "Igbo" },
  { code: "zu", name: "Zulu", nativeName: "isiZulu" },
  { code: "af", name: "Afrikaans", nativeName: "Afrikaans" },
  { code: "bg", name: "Bulgarian", nativeName: "Български" },
  { code: "hr", name: "Croatian", nativeName: "Hrvatski" },
  { code: "sk", name: "Slovak", nativeName: "Slovenčina" },
  { code: "sl", name: "Slovenian", nativeName: "Slovenščina" },
  { code: "lt", name: "Lithuanian", nativeName: "Lietuvių" },
  { code: "lv", name: "Latvian", nativeName: "Latviešu" },
  { code: "et", name: "Estonian", nativeName: "Eesti" },
  { code: "hu", name: "Hungarian", nativeName: "Magyar" },
  { code: "sq", name: "Albanian", nativeName: "Shqip" },
  { code: "mk", name: "Macedonian", nativeName: "Македонски" },
  { code: "bs", name: "Bosnian", nativeName: "Bosanski" },
  { code: "sr", name: "Serbian", nativeName: "Српски" },
  { code: "mn", name: "Mongolian", nativeName: "Монгол" },
  { code: "ne", name: "Nepali", nativeName: "नेपाली" },
  { code: "si", name: "Sinhala", nativeName: "සිංහල" },
  { code: "my", name: "Burmese", nativeName: "မြန်မာ" },
  { code: "km", name: "Khmer", nativeName: "ភាសាខ្មែរ" },
  { code: "lo", name: "Lao", nativeName: "ລາວ" },
  { code: "tg", name: "Tajik", nativeName: "Тоҷикӣ" },
  { code: "uz", name: "Uzbek", nativeName: "Oʻzbek" },
  { code: "kk", name: "Kazakh", nativeName: "Қазақ" },
  { code: "ky", name: "Kyrgyz", nativeName: "Кыргызча" },
  { code: "az", name: "Azerbaijani", nativeName: "Azərbaycan" },
  { code: "tk", name: "Turkmen", nativeName: "Türkmen" },
  { code: "so", name: "Somali", nativeName: "Soomaali" },
  { code: "mg", name: "Malagasy", nativeName: "Malagasy" },
  { code: "sn", name: "Shona", nativeName: "chiShona" },
  { code: "rw", name: "Kinyarwanda", nativeName: "Ikinyarwanda" },
  { code: "ny", name: "Chichewa", nativeName: "Chichewa" },
  { code: "st", name: "Sesotho", nativeName: "Sesotho" },
  { code: "tn", name: "Tswana", nativeName: "Setswana" },
  { code: "ts", name: "Tsonga", nativeName: "Xitsonga" },
  { code: "ve", name: "Venda", nativeName: "Tshivenḓa" },
  { code: "ss", name: "Swati", nativeName: "siSwati" },
] as const;

export type LanguageCode = (typeof LANGUAGES)[number]["code"];

const LANGUAGE_MAP = new Map<string, typeof LANGUAGES[number]>(LANGUAGES.map(l => [l.code, l]));

export function findLanguage(code: string): typeof LANGUAGES[number] | undefined {
  return LANGUAGE_MAP.get(code);
}

export const DEFAULT_LANGUAGE: { code: string; name: string; nativeName: string } = LANGUAGE_MAP.get("en")!;

// ISO 639-3 → ISO 639-1 (for franc library)
const ISO639_3_TO_1: Record<string, string> = {
  ara: "ar", eng: "en", fra: "fr", spa: "es", deu: "de",
  por: "pt", ita: "it", nld: "nl", rus: "ru", jpn: "ja",
  kor: "ko", zho: "zh", hin: "hi", urd: "ur", tur: "tr",
  fas: "fa", ind: "id", msa: "ms", tha: "th", vie: "vi",
  pol: "pl", swe: "sv", nob: "no", dan: "da", fin: "fi",
  ces: "cs", ron: "ro", ukr: "uk", ell: "el", heb: "he",
  swa: "sw", ben: "bn", tam: "ta", tel: "te", mar: "mr",
  guj: "gu", kan: "kn", mal: "ml", pan: "pa", hye: "hy",
  kat: "ka", amh: "am", hau: "ha", yor: "yo", ibo: "ig",
  zul: "zu", afr: "af", bul: "bg", hrv: "hr", slk: "sk",
  slv: "sl", lit: "lt", lav: "lv", est: "et", hun: "hu",
  sqi: "sq", mkd: "mk", bos: "bs", srp: "sr", mon: "mn",
  nep: "ne", sin: "si", mya: "my", khm: "km", lao: "lo",
  tgk: "tg", uzb: "uz", kaz: "kk", kir: "ky", azj: "az",
  tuk: "tk", som: "so", mlg: "mg", sna: "sn", kin: "rw",
  nya: "ny", sot: "st", tsn: "tn", tso: "ts", ven: "ve",
  ssw: "ss",
};

export function findLanguageByISO639_3(code3: string): typeof LANGUAGES[number] | undefined {
  let code1 = ISO639_3_TO_1[code3];
  if (!code1) return undefined;
  return LANGUAGE_MAP.get(code1);
}
